apiVersion: apps/v1
kind: Deployment
metadata:
  name: failing-app
spec:
  selector:
    matchLabels:
      app: failing-app
  replicas: 1
  template:
    metadata:
      labels:
        app: failing-app
    spec:
      containers:
        - name: failing-app
          image: fritzduchardt/k8s-showcase-application
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - "sleep 30 && curl -X POST http://localhost:9090/shutdown &"
