apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  ports:
    - port: 80
      name: application
      protocol: TCP
      targetPort: 8080
  selector:
    app: apigateway
