apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app
  name: web-app
spec:
  type: NodePort
  ports:
    - port: 8080
      name: application
      protocol: TCP
      targetPort: 8080
    - port: 9090
      name: health
      protocol: TCP
      targetPort: 9090
  selector:
    app: external-server
