apiVersion: v1
data:
  default.conf: |

    server {
        listen       88;
        server_name  localhost;

        location / {
            proxy_pass http://localhost:8080/;
        }

    }

kind: ConfigMap
metadata:
  name: nginxconfig
