apiVersion: v1
kind: Pod
metadata:
  labels:
    run: postgres
  name: postgres
spec:
  hostname: mypod
  subdomain: theserver
  containers:
    - env:
        - name: POSTGRES_PASSWORD
          value: super-safe-passwd
      image: postgres
      imagePullPolicy: Always
      name: postgres
      resources: {}
