apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:

spec:
  containers:
    - name: my-container
      image: nginx
      readinessProbe:
        httpGet:
          port: 80
      resources:
        requests:
          cpu: 1

