apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spacefiller
  name: spacefiller
spec:
  containers:
    - image: fritzduchardt/k8s-showcase-application
      imagePullPolicy: Always
      name: k8sshowcase
      env:
        - name: SPRING_PROFLES_ACTIVE
          value: nodb
      resources:
        limits:
          ephemeral-storage: "100Mi"
      volumeMounts:
        - mountPath: /tmp
          name: host
  nodeSelector:
    kubernetes.io/hostname: yet-another-pool-3pxhytp4be
  volumes:
    - name: host
      emptyDir: {}
