apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clone
  name: clone
spec:
  replicas: 50
  selector:
    matchLabels:
      app: clone
  template:
    metadata:
      labels:
        app: clone
    spec:
      containers:
        - image: fritzduchardt/k8s-showcase-application
          imagePullPolicy: Always
          name: clone