apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spacefiller
  name: spacefiller
spec:
  containers:
    - image: fritzduchardt/k8s-showcase-application
      imagePullPolicy: Always
      name: k8sshowcase
      env:
        - name: SPRING_PROFLES_ACTIVE
          value: nodb
      volumeMounts:
        - mountPath: /tmp
          name: host
  volumes:
    - name: host
      hostPath:
        path: /data