apiVersion: v1
kind: Pod
metadata:
  labels:
    run: privileged
  name: privileged2
spec:
  containers:
  - args:
    - tail
    - -f
    - /dev/null
    image: ubuntu
    name: ubuntu
    resources: {}
    volumeMounts:
      - mountPath: /rootfs
        name: var
  nodeSelector:
    kubernetes.io/hostname: yet-another-pool-3pxhytp4be
  volumes:
    - name: var
      hostPath:
         path: /
