apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: moneyapp
  name: moneyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moneyapp
  template:
    metadata:
      labels:
        app: moneyapp
    spec:
      containers:
        - image: fritzduchardt/k8s-showcase-application:latest
          imagePullPolicy: Always
          name: moneyapp
          env:
            - name: STORAGE_FOLDER_PATH
              value: /money-cache
          volumeMounts:
            - mountPath: /tmp
              name: persistent-volume
          readinessProbe:
            httpGet:
              port: 9090
              path: /health
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: moneyapp-claim
