apiVersion: v1
kind: Service
metadata:
  labels:
    app: cryptoapp
  name: cryptoapp
spec:
  ports:
    - port: 8080
      name: application
      protocol: TCP
      targetPort: 8080
    - port: 9090
      name: health
      protocol: TCP
      targetPort: 9090
  selector:
    app: cryptoapp
