apiVersion: v1
kind: Pod
metadata:
  labels:
    app: client
  name: client
spec:
  containers:
    - image: curlimages/curl:7.71.1
      imagePullPolicy: IfNotPresent
      name: curl
      command:
        - sh
        - -c
        - tail -f /dev/null
