apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: downstream-deployment
  name: downstream-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downstream-deployment
  template:
    metadata:
      labels:
        app: downstream-deployment
    spec:
      containers:
        - image: fritzduchardt/k8s-showcase-application:latest
          imagePullPolicy: Always
          name: downstream-deployment
          livenessProbe:
            httpGet:
              port: 9090
              path: /health
