apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    run: postgres
  clusterIP: None
  ports:
    - name: foo # Actually, no port is needed.
      port: 80
      targetPort: 8080