apiVersion: v1
kind: Service
metadata:
  labels:
    app: upstream-deployment
  name: upstream-deployment
spec:
  ports:
    - port: 8080
      name: application
      protocol: TCP
      targetPort: 8080
  selector:
    app: upstream-deployment
