apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: back-app
  name: back-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-app
  template:
    metadata:
      labels:
        app: back-app
    spec:
      containers:
        - image: fritzduchardt/k8s-showcase-application:latest
          imagePullPolicy: Always
          name: back-app
          env:
            - name: STORAGE_FOLDER_PATH
              value: /money-cache
            - name: SPRING_PROFILES_ACTIVE
              value: nodb
          volumeMounts:
            - mountPath: /tmp
              name: persistent-volume
          readinessProbe:
            httpGet:
              port: 9090
              path: /health
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: back-app-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: back-app-claim
  labels:
    app: back-app-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ionos-enterprise-hdd
  resources:
    requests:
      storage: 1Gi
