apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-app
  labels:
    app: web-app
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi