apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - image: fritzduchardt/k8s-showcase-application:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: nodb
          name: web-app
          volumeMounts:
            - mountPath: /tmp
              name: persistent-volume
          readinessProbe:
            httpGet:
              port: 9090
              path: /health
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: web-app
