apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  hostname: pod1
  subdomain: n-ginx
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
