apiVersion: v1
data:
  default.conf: |
    server {
        listen       88;
        listen  [::]:80;
        server_name  localhost;

        location / {
            proxy_pass http://localhost:8080/;
        }

        location /swagger {
            proxy_pass http://localhost:8081/;
        }

    }
kind: ConfigMap
metadata:
  name: nginxconfig
  namespace: default