apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxied-server
  name: proxied-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxied-server
  template:
    metadata:
      labels:
        app: proxied-server
    spec:
      containers:
        - image: fritzduchardt/k8s-showcase-application:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: nodb
          imagePullPolicy: Always
          name: proxied-server
          livenessProbe:
            httpGet:
              port: 9090
              path: /health
        - image: nginx:latest
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: nginx-conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginxconfig
