apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxied-server
  name: proxied-server
spec:
  ports:
    - port: 80
      name: application
      protocol: TCP
      targetPort: 80
  selector:
    app: proxied-server
